# Generated by Django 2.0.7 on 2018-07-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('elements', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
    ]
