# Generated by Django 2.0.7 on 2018-07-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_information', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Phantom_Open_Emoji_1f379.svg/480px-Phantom_Open_Emoji_1f379.svg.png', upload_to=''),
        ),
    ]
